// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzIuL7NMdoSeqwh_gHG8TtM6Lm9kA9FY',
    appId: '1:1080816862730:android:04d0b14651a62dc93601f3',
    messagingSenderId: '1080816862730',
    projectId: 'serves-ltxnrk',
    storageBucket: 'serves-ltxnrk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVl2NQUIPwKd5N89hvmXD2XsqPVm7KQ6Y',
    appId: '1:1080816862730:ios:ad57fcdd78913a273601f3',
    messagingSenderId: '1080816862730',
    projectId: 'serves-ltxnrk',
    storageBucket: 'serves-ltxnrk.appspot.com',
    iosBundleId: 'com.cargurus.userapp.cargurus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwvrKJMLR3pmm0CR65hnmhimi1f06jgmk',
    appId: '1:1080816862730:web:927a35dc9655fe933601f3',
    messagingSenderId: '1080816862730',
    projectId: 'serves-ltxnrk',
    authDomain: 'serves-ltxnrk.firebaseapp.com',
    storageBucket: 'serves-ltxnrk.appspot.com',
  );

}